name: Bump version
on:
   push:
      branches:
        - main

jobs:
   create-container:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: azure/docker-login@v1
          with:
             login-server: asaeenfuseacr.azurecr.io
             username: ${{ secrets.ACR_USERNAME }}
             password: ${{ secrets.ACR_PASSWORD }}
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZ_CREDENTIALS }}
        - run: az config set extension.use_dynamic_install=yes_without_prompt
        - run: docker build  -f Dockerfile . -t asaeenfuseacr.azurecr.io/store-genius:v${{ github.run_number }} --build-arg BUILD_ENV=prod  --build-arg MATTERPORT_API_KEY=${{ secrets.MATTERPORT_API_KEY }}

        - run: docker push asaeenfuseacr.azurecr.io/store-genius:v${{ github.run_number }}
        - run: |
            az spring app deploy -s asae-enfuse-sandbox -g asaeSandbox -n store-genius --container-image store-genius:v${{ github.run_number }} --container-registry asaeenfuseacr.azurecr.io --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }}
